title: Crea Receptions
description: Le site web du traiteur évenementiel Crea Receptions

baseurl: "" # The subfolder where the site will live, no trailing slash. Ex: "/investors/reports/2019"
url: "http://localhost:4000" # The base url, no trailing slash. Ex: "https://www.example.com"

is_production: false # Leave unchanged. Used for production build.

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
